## 02. Device Feature Engineering

### Objective

- Load device.csv
- Understand device usage behavior
- Engineer employee-level USB/device features
- Save device_features.csv

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Define Dataset Path
DATA_PATH = Path("../DATA/raw/CERT_R6.2/data")

In [3]:
# Load Device Dataset
device = pd.read_csv(DATA_PATH / "device.csv")

In [4]:
device.head()

,id,date,user,pc,file_tree,activity
0,{Z2Q8-K3AV28BE-9353JIRT},01/02/2010 07:17:18,SDH2394,PC-5849,R:\;R:\22B5gX4;R:\SDH2394,Connect
1,{C7F1-G7LE60RU-2483DAXS},01/02/2010 07:22:42,JKS2444,PC-6961,R:\;R:\JKS2444,Connect
2,{T9A4-D4RV69OF-1704NINW},01/02/2010 07:31:42,CBA1023,PC-1570,R:\;R:\42gY283;R:\48rr4y2;R:\59ntt61;R:\76xCQG...,Connect
3,{S8L0-O6QQ15NL-0636OYNV},01/02/2010 07:33:28,GNT0221,PC-6427,R:\;R:\GNT0221,Connect
4,{U0F1-R1FX27FM-6954TTVU},01/02/2010 07:33:55,JKS2444,PC-6961,NaN,Disconnect

In [5]:
device.tail()

,id,date,user,pc,file_tree,activity
1551823,{H8F7-C0ZV44EZ-8096IKGM},05/31/2011 23:02:16,WSA1765,PC-7733,NaN,Disconnect
1551824,{I8V0-G3ID86HT-3033NLGV},05/31/2011 23:31:40,ABD3426,PC-8657,R:\;R:\ABD3426,Connect
1551825,{T5I0-I7MC85ZR-6708PJZP},05/31/2011 23:36:13,ABD3426,PC-8657,NaN,Disconnect
1551826,{A2P9-L4MQ58YG-5271LLTI},05/31/2011 23:46:23,QAH0048,PC-6551,R:\;R:\363xgw8;R:\QAH0048,Connect
1551827,{W8T4-C2KD24IB-0179YZLW},05/31/2011 23:51:13,QAH0048,PC-6551,NaN,Disconnect

In [6]:
device.shape

(1551828, 6)

In [7]:
device.columns

Index(['id', 'date', 'user', 'pc', 'file_tree', 'activity'], dtype='str')

In [8]:
device.info()

<class 'pandas.DataFrame'>
RangeIndex: 1551828 entries, 0 to 1551827
Data columns (total 6 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   id         1551828 non-null  str
 1   date       1551828 non-null  str
 2   user       1551828 non-null  str
 3   pc         1551828 non-null  str
 4   file_tree  778354 non-null   str
 5   activity   1551828 non-null  str
dtypes: str(6)
memory usage: 195.4 MB

In [9]:
# Statistical Summary
device.describe(include="all")

,id,date,user,pc,file_tree,activity
count,1551828,1551828,1551828,1551828,778354,1551828
unique,1551828,1475524,788,3829,788,2
top,{Z2Q8-K3AV28BE-9353JIRT},04/09/2010 13:13:53,CJM0273,PC-3471,R:\;R:\13jd423;R:\49FP5C2;R:\51n6647;R:\CJM0273,Connect
freq,1,15,8696,8702,4355,778354

In [10]:
#check for missing values
device.isnull().sum()

id                0
date              0
user              0
pc                0
file_tree    773474
activity          0
dtype: int64

In [11]:
#check duplicates records
device.duplicated().sum()

np.int64(0)

In [12]:
# Check Unique Users
device["user"].nunique()

788

In [13]:
# Check Activity Types
device["activity"].value_counts()

activity
Connect       778354
Disconnect    773474
Name: count, dtype: int64

In [14]:
# Convert Date Column to Datetime
device["date"] = pd.to_datetime(device["date"])

In [15]:
# Extract Date Features
device["year"] = device["date"].dt.year
device["month"] = device["date"].dt.month
device["day"] = device["date"].dt.day
device["hour"] = device["date"].dt.hour
device["weekday"] = device["date"].dt.day_name()

In [16]:
device.head()

,id,date,user,pc,file_tree,activity,year,month,day,hour,weekday
0,{Z2Q8-K3AV28BE-9353JIRT},2010-01-02 07:17:18,SDH2394,PC-5849,R:\;R:\22B5gX4;R:\SDH2394,Connect,2010,1,2,7,Saturday
1,{C7F1-G7LE60RU-2483DAXS},2010-01-02 07:22:42,JKS2444,PC-6961,R:\;R:\JKS2444,Connect,2010,1,2,7,Saturday
2,{T9A4-D4RV69OF-1704NINW},2010-01-02 07:31:42,CBA1023,PC-1570,R:\;R:\42gY283;R:\48rr4y2;R:\59ntt61;R:\76xCQG...,Connect,2010,1,2,7,Saturday
3,{S8L0-O6QQ15NL-0636OYNV},2010-01-02 07:33:28,GNT0221,PC-6427,R:\;R:\GNT0221,Connect,2010,1,2,7,Saturday
4,{U0F1-R1FX27FM-6954TTVU},2010-01-02 07:33:55,JKS2444,PC-6961,NaN,Disconnect,2010,1,2,7,Saturday

In [17]:
# Create After Hours Feature
device["after_hours"] = (
    (device["hour"] < 8) |
    (device["hour"] >= 18)
)

In [18]:
# Create Weekend Activity Feature
device["weekend_activity"] = device["weekday"].isin(
    ["Saturday", "Sunday"]
)

In [19]:
device.head()

,id,date,user,pc,file_tree,activity,year,month,day,hour,weekday,after_hours,weekend_activity
0,{Z2Q8-K3AV28BE-9353JIRT},2010-01-02 07:17:18,SDH2394,PC-5849,R:\;R:\22B5gX4;R:\SDH2394,Connect,2010,1,2,7,Saturday,True,True
1,{C7F1-G7LE60RU-2483DAXS},2010-01-02 07:22:42,JKS2444,PC-6961,R:\;R:\JKS2444,Connect,2010,1,2,7,Saturday,True,True
2,{T9A4-D4RV69OF-1704NINW},2010-01-02 07:31:42,CBA1023,PC-1570,R:\;R:\42gY283;R:\48rr4y2;R:\59ntt61;R:\76xCQG...,Connect,2010,1,2,7,Saturday,True,True
3,{S8L0-O6QQ15NL-0636OYNV},2010-01-02 07:33:28,GNT0221,PC-6427,R:\;R:\GNT0221,Connect,2010,1,2,7,Saturday,True,True
4,{U0F1-R1FX27FM-6954TTVU},2010-01-02 07:33:55,JKS2444,PC-6961,NaN,Disconnect,2010,1,2,7,Saturday,True,True

In [20]:
# Create Employee Device Profile
device_profile = (
    device.groupby("user")
          .size()
          .reset_index(name="total_device_events")
)

In [21]:
# Calculate Total Connect Events Per User
total_connects = (
    device[device["activity"] == "Connect"]
    .groupby("user")
    .size()
    .reset_index(name="total_connects")
)

In [22]:
# Merge Total Connect Events
device_profile = device_profile.merge(
    total_connects,
    on="user",
    how="left"
)

In [23]:
# Calculate Total Disconnect Events
total_disconnects = (
    device[device["activity"] == "Disconnect"]
    .groupby("user")
    .size()
    .reset_index(name="total_disconnects")
)

In [24]:
# Merge Total Disconnect Events
device_profile = device_profile.merge(
    total_disconnects,
    on="user",
    how="left"
)
device_profile.head()

      user  total_device_events  total_connects  total_disconnects
0  AAC0610                  700             351                349
1  AAF0819                 2056            1032               1024
2  AAP0352                 1420             713                707
3  AAP1919                 6159            3089               3070
4  ABD3426                 7979            4000               3979

In [25]:
# Calculate After-Hours Device Events Per User
after_hours_device = (
    device[device["after_hours"]]
    .groupby("user")
    .size()
    .reset_index(name="after_hours_device_events")
)

In [26]:
# Merge After-Hours Device Events
device_profile = device_profile.merge(
    after_hours_device,
    on="user",
    how="left"
)
device_profile.head()

,user,total_device_events,total_connects,total_disconnects,after_hours_device_events
0,AAC0610,700,351,349,8.0
1,AAF0819,2056,1032,1024,33.0
2,AAP0352,1420,713,707,31.0
3,AAP1919,6159,3089,3070,120.0
4,ABD3426,7979,4000,3979,83.0

In [27]:
# Calculate Weekend Device Events Per User
weekend_device = (
    device[device["weekend_activity"]]
    .groupby("user")
    .size()
    .reset_index(name="weekend_device_events")
)
weekend_device.head()

      user  weekend_device_events
0  ABD3426                   1742
1  ABK3081                     38
2  ABM3687                    158
3  ABP2917                    146
4  ACB0701                     28

In [28]:
# Merge Weekend Device Events
device_profile = device_profile.merge(
    weekend_device,
    on="user",
    how="left"
)
device_profile.head()

,user,total_device_events,total_connects,total_disconnects,after_hours_device_events,weekend_device_events
0,AAC0610,700,351,349,8.0,NaN
1,AAF0819,2056,1032,1024,33.0,NaN
2,AAP0352,1420,713,707,31.0,NaN
3,AAP1919,6159,3089,3070,120.0,NaN
4,ABD3426,7979,4000,3979,83.0,1742.0

In [29]:
# Fill Missing Values
device_profile = device_profile.fillna(0)

In [30]:
# Display Employee Device Profile
device_profile.head()

,user,total_device_events,total_connects,total_disconnects,after_hours_device_events,weekend_device_events
0,AAC0610,700,351,349,8.0,0.0
1,AAF0819,2056,1032,1024,33.0,0.0
2,AAP0352,1420,713,707,31.0,0.0
3,AAP1919,6159,3089,3070,120.0,0.0
4,ABD3426,7979,4000,3979,83.0,1742.0

In [31]:
#check dataset information
device_profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 788 entries, 0 to 787
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   user                       788 non-null    str
 1   total_device_events        788 non-null    int64
 2   total_connects             788 non-null    int64
 3   total_disconnects          788 non-null    int64
 4   after_hours_device_events  788 non-null    float64
 5   weekend_device_events      788 non-null    float64
dtypes: float64(2), int64(3), str(1)
memory usage: 42.5 KB

In [32]:
# Save Device Features
FEATURE_PATH = Path("../DATA/features")
FEATURE_PATH.mkdir(parents=True, exist_ok=True)

device_profile.to_csv(
    FEATURE_PATH / "device_features.csv",
    index=False
)

print("device_features.csv saved successfully!")

device_features.csv saved successfully!