In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
DATA_PATH = Path("../DATA/raw/CERT_R6.2/data")

In [3]:
file = pd.read_csv(DATA_PATH / "file.csv")

In [4]:
file.head()

,id,date,user,pc,filename,activity,to_removable_media,from_removable_media,content
0,{F3E2-X3MV05YQ-3516SZDT},01/02/2010 07:19:41,SDH2394,PC-5849,R:\60WBQE7S.doc,File Open,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Ernesztin's brother, L..."
1,{I6N1-Z7VL92UY-8715ESKQ},01/02/2010 07:21:30,SDH2394,PC-5849,R:\0VGILDW8.pdf,File Write,True,False,25-50-44-46-2D ---- Bengali As do many other T...
2,{G4X5-J7MH70FV-8936QVSB},01/02/2010 07:22:11,SDH2394,PC-5849,R:\60WBQE7S.doc,File Copy,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Ernesztin's brother, L..."
3,{M2M7-Z5ST21EU-6704NSKO},01/02/2010 07:24:06,SDH2394,PC-5849,R:\22B5gX4\H8Y96RRE.doc,File Write,True,False,D0-CF-11-E0-A1-B1-1A-E1 After the death of his...
4,{R0A9-O9XB25PE-9236MALV},01/02/2010 07:24:45,SDH2394,PC-5849,R:\SDH2394\7XRCV2N5.pdf,File Copy,True,False,25-50-44-46-2D Although he restored some of th...

In [5]:
file.tail()

,id,date,user,pc,filename,activity,to_removable_media,from_removable_media,content
2014878,{R8J5-L3EX86SE-2587NGZX},05/31/2011 23:36:00,ABD3426,PC-8657,R:\ABD3426\ZLKK3YO7.doc,File Delete,False,True,"D0-CF-11-E0-A1-B1-1A-E1 However, as the demand..."
2014879,{V9N4-W1HU28IK-2801HPQB},05/31/2011 23:47:51,QAH0048,PC-6551,R:\363xgw8\VZIJJ9K4.doc,File Open,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Another ancestor, Edmu..."
2014880,{T3K2-A5FA51RT-7052TPBR},05/31/2011 23:48:23,QAH0048,PC-6551,R:\363xgw8\VZIJJ9K4.doc,File Open,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Another ancestor, Edmu..."
2014881,{N1R7-T1ZF91JI-6862OZIR},05/31/2011 23:49:13,QAH0048,PC-6551,R:\363xgw8\VZIJJ9K4.doc,File Open,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Another ancestor, Edmu..."
2014882,{A0M1-D9IB92CH-4369ZYNE},05/31/2011 23:49:56,QAH0048,PC-6551,R:\363xgw8\VZIJJ9K4.doc,File Delete,False,True,"D0-CF-11-E0-A1-B1-1A-E1 Another ancestor, Edmu..."

In [6]:
file.shape

(2014883, 9)

In [7]:
file.columns

Index(['id', 'date', 'user', 'pc', 'filename', 'activity',
       'to_removable_media', 'from_removable_media', 'content'],
      dtype='str')

In [8]:
file.info()

<class 'pandas.DataFrame'>
RangeIndex: 2014883 entries, 0 to 2014882
Data columns (total 9 columns):
 #   Column                Dtype
---  ------                -----
 0   id                    str
 1   date                  str
 2   user                  str
 3   pc                    str
 4   filename              str
 5   activity              str
 6   to_removable_media    bool
 7   from_removable_media  bool
 8   content               str
dtypes: bool(2), str(7)
memory usage: 1.3 GB

In [9]:
#check missing values
file.isnull().sum()

id                      0
date                    0
user                    0
pc                      0
filename                0
activity                0
to_removable_media      0
from_removable_media    0
content                 0
dtype: int64

In [10]:
file.duplicated().sum()

np.int64(0)

In [11]:
# Convert Date Column to Datetime
file["date"] = pd.to_datetime(file["date"])

In [12]:
file["date"].head()

0   2010-01-02 07:19:41
1   2010-01-02 07:21:30
2   2010-01-02 07:22:11
3   2010-01-02 07:24:06
4   2010-01-02 07:24:45
Name: date, dtype: datetime64[us]

In [13]:
file["date"].dtype

dtype('<M8[us]')

In [14]:
# Extract Date and Time Features
file["year"] = file["date"].dt.year
file["month"] = file["date"].dt.month
file["day"] = file["date"].dt.day
file["hour"] = file["date"].dt.hour
file["weekday"] = file["date"].dt.day_name()

In [15]:
file[
    ["date", "year", "month", "day", "hour", "weekday"]
].head()

                 date  year  month  day  hour   weekday
0 2010-01-02 07:19:41  2010      1    2     7  Saturday
1 2010-01-02 07:21:30  2010      1    2     7  Saturday
2 2010-01-02 07:22:11  2010      1    2     7  Saturday
3 2010-01-02 07:24:06  2010      1    2     7  Saturday
4 2010-01-02 07:24:45  2010      1    2     7  Saturday

In [16]:
# Create After-Hours and Weekend Features
file["after_hours"] = (
    (file["hour"] < 8) |
    (file["hour"] >= 18)
)

file["weekend_activity"] = file["weekday"].isin(
    ["Saturday", "Sunday"]
)

In [17]:
file[
    ["hour", "weekday", "after_hours", "weekend_activity"]
].head()

   hour   weekday  after_hours  weekend_activity
0     7  Saturday         True              True
1     7  Saturday         True              True
2     7  Saturday         True              True
3     7  Saturday         True              True
4     7  Saturday         True              True

In [18]:
# Explore File Activities
file["activity"].value_counts()

activity
File Copy      725458
File Open      657500
File Delete    380799
File Write     251126
Name: count, dtype: int64

In [19]:
# Create Initial Employee File Profile
file_profile = (
    file.groupby("user")
        .size()
        .reset_index(name="total_file_events")
)

In [20]:
file_profile.head()

      user  total_file_events
0  AAB0162                 30
1  AAB0398                 36
2  AAC0610               1851
3  AAC0668                 62
4  AAC3270                  8

In [21]:
# Calculate File Open Count
file_open = (
    file[file["activity"] == "File Open"]
    .groupby("user")
    .size()
    .reset_index(name="file_open_count")
)

In [22]:
file_open.head()

      user  file_open_count
0  AAB0162               30
1  AAB0398               36
2  AAC0610              387
3  AAC0668               62
4  AAC3270                8

In [23]:
# Merge File Open Count
file_profile = file_profile.merge(
    file_open,
    on="user",
    how="left"
)
file_profile.head()

      user  total_file_events  file_open_count
0  AAB0162                 30               30
1  AAB0398                 36               36
2  AAC0610               1851              387
3  AAC0668                 62               62
4  AAC3270                  8                8

In [24]:
# Calculate File Copy Count
file_copy = (
    file[file["activity"] == "File Copy"]
    .groupby("user")
    .size()
    .reset_index(name="file_copy_count")
)

In [25]:
file_copy.head()

      user  file_copy_count
0  AAC0610              825
1  AAF0819             1480
2  AAP0352              285
3  AAP1919              197
4  ABD3426             5158

In [26]:
# Merge File Copy Count
file_profile = file_profile.merge(
    file_copy,
    on="user",
    how="left"
)

In [27]:
file_profile.head()

      user  total_file_events  file_open_count  file_copy_count
0  AAB0162                 30               30              NaN
1  AAB0398                 36               36              NaN
2  AAC0610               1851              387            825.0
3  AAC0668                 62               62              NaN
4  AAC3270                  8                8              NaN

In [28]:
# Calculate File Write Count
file_write = (
    file[file["activity"] == "File Write"]
    .groupby("user")
    .size()
    .reset_index(name="file_write_count")
)

In [29]:
# Merge File Write Count
file_profile = file_profile.merge(
    file_write,
    on="user",
    how="left"
)

In [30]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count
0,AAB0162,30,30,NaN,NaN
1,AAB0398,36,36,NaN,NaN
2,AAC0610,1851,387,825.0,235.0
3,AAC0668,62,62,NaN,NaN
4,AAC3270,8,8,NaN,NaN

In [31]:
# Calculate File Delete Count
file_delete = (
    file[file["activity"] == "File Delete"]
    .groupby("user")
    .size()
    .reset_index(name="file_delete_count")
)

In [32]:
# Merge File Delete Count
file_profile = file_profile.merge(
    file_delete,
    on="user",
    how="left"
)

In [33]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count
0,AAB0162,30,30,NaN,NaN,NaN
1,AAB0398,36,36,NaN,NaN,NaN
2,AAC0610,1851,387,825.0,235.0,404.0
3,AAC0668,62,62,NaN,NaN,NaN
4,AAC3270,8,8,NaN,NaN,NaN

In [34]:
# Calculate Files Copied to Removable Media
to_removable = (
    file[file["to_removable_media"]]
    .groupby("user")
    .size()
    .reset_index(name="files_to_removable_media")
)

In [35]:
to_removable.head()

      user  files_to_removable_media
0  AAC0610                       604
1  AAF0819                      1036
2  AAP0352                       219
3  AAP1919                       144
4  ABD3426                      3936

In [36]:
# Calculate Files Copied From Removable Media
from_removable = (
    file[file["from_removable_media"]]
    .groupby("user")
    .size()
    .reset_index(name="files_from_removable_media")
)

In [37]:
from_removable.head()

      user  files_from_removable_media
0  AAC0610                        1056
1  AAF0819                        2003
2  AAP0352                         373
3  AAP1919                         245
4  ABD3426                        6472

In [38]:
# Merge Removable Media Features
file_profile = file_profile.merge(
    to_removable,
    on="user",
    how="left"
)

file_profile = file_profile.merge(
    from_removable,
    on="user",
    how="left"
)

In [39]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media
0,AAB0162,30,30,NaN,NaN,NaN,NaN,NaN
1,AAB0398,36,36,NaN,NaN,NaN,NaN,NaN
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0
3,AAC0668,62,62,NaN,NaN,NaN,NaN,NaN
4,AAC3270,8,8,NaN,NaN,NaN,NaN,NaN

In [40]:
# Calculate Unique Files Accessed
unique_files = (
    file.groupby("user")["filename"]
        .nunique()
        .reset_index(name="unique_files")
)

In [41]:
unique_files.head()

      user  unique_files
0  AAB0162             8
1  AAB0398             7
2  AAC0610           641
3  AAC0668             8
4  AAC3270             2

In [42]:
# Calculate Unique Computers Used
unique_pcs = (
    file.groupby("user")["pc"]
        .nunique()
        .reset_index(name="unique_pcs")
)

In [43]:
unique_pcs.head()

      user  unique_pcs
0  AAB0162           1
1  AAB0398           1
2  AAC0610           1
3  AAC0668           1
4  AAC3270           1

In [44]:
# Calculate After-Hours File Activity
after_hours_activity = (
    file[file["after_hours"]]
    .groupby("user")
    .size()
    .reset_index(name="after_hours_file_activity")
)

In [45]:
# Calculate Weekend File Activity
weekend_files = (
    file[file["weekend_activity"]]
    .groupby("user")
    .size()
    .reset_index(name="weekend_file_count")
)

In [46]:
weekend_files.head()

      user  weekend_file_count
0  AAS3428                  19
1  ABD3426                2515
2  ABK3081                  74
3  ABM3203                  67
4  ABM3641                   9

In [47]:
# Merge Unique Files Feature
file_profile = file_profile.merge(
    unique_files,
    on="user",
    how="left"
)

In [48]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files
0,AAB0162,30,30,NaN,NaN,NaN,NaN,NaN,8
1,AAB0398,36,36,NaN,NaN,NaN,NaN,NaN,7
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0,641
3,AAC0668,62,62,NaN,NaN,NaN,NaN,NaN,8
4,AAC3270,8,8,NaN,NaN,NaN,NaN,NaN,2

In [49]:
# Merge Unique PCs Feature
file_profile = file_profile.merge(
    unique_pcs,
    on="user",
    how="left"
)

In [50]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files,unique_pcs
0,AAB0162,30,30,NaN,NaN,NaN,NaN,NaN,8,1
1,AAB0398,36,36,NaN,NaN,NaN,NaN,NaN,7,1
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0,641,1
3,AAC0668,62,62,NaN,NaN,NaN,NaN,NaN,8,1
4,AAC3270,8,8,NaN,NaN,NaN,NaN,NaN,2,1

In [51]:
# Merge After-Hours File Activity
file_profile = file_profile.merge(
    after_hours_activity,
    on="user",
    how="left"
)

In [52]:
# Merge Weekend File Activity
file_profile = file_profile.merge(
    weekend_files,
    on="user",
    how="left"
)

In [53]:
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files,unique_pcs,after_hours_file_activity,weekend_file_count
0,AAB0162,30,30,NaN,NaN,NaN,NaN,NaN,8,1,4.0,NaN
1,AAB0398,36,36,NaN,NaN,NaN,NaN,NaN,7,1,2.0,NaN
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0,641,1,8.0,NaN
3,AAC0668,62,62,NaN,NaN,NaN,NaN,NaN,8,1,NaN,NaN
4,AAC3270,8,8,NaN,NaN,NaN,NaN,NaN,2,1,NaN,NaN

In [54]:
# Fill Missing Values
file_profile = file_profile.fillna(0)

In [55]:
file_profile.isnull().sum()

user                          0
total_file_events             0
file_open_count               0
file_copy_count               0
file_write_count              0
file_delete_count             0
files_to_removable_media      0
files_from_removable_media    0
unique_files                  0
unique_pcs                    0
after_hours_file_activity     0
weekend_file_count            0
dtype: int64

In [56]:
# Verify the Final File Profile
file_profile.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files,unique_pcs,after_hours_file_activity,weekend_file_count
0,AAB0162,30,30,0.0,0.0,0.0,0.0,0.0,8,1,4.0,0.0
1,AAB0398,36,36,0.0,0.0,0.0,0.0,0.0,7,1,2.0,0.0
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0,641,1,8.0,0.0
3,AAC0668,62,62,0.0,0.0,0.0,0.0,0.0,8,1,0.0,0.0
4,AAC3270,8,8,0.0,0.0,0.0,0.0,0.0,2,1,0.0,0.0

In [57]:
file_profile.info()

<class 'pandas.DataFrame'>
RangeIndex: 3185 entries, 0 to 3184
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user                        3185 non-null   str
 1   total_file_events           3185 non-null   int64
 2   file_open_count             3185 non-null   int64
 3   file_copy_count             3185 non-null   float64
 4   file_write_count            3185 non-null   float64
 5   file_delete_count           3185 non-null   float64
 6   files_to_removable_media    3185 non-null   float64
 7   files_from_removable_media  3185 non-null   float64
 8   unique_files                3185 non-null   int64
 9   unique_pcs                  3185 non-null   int64
 10  after_hours_file_activity   3185 non-null   float64
 11  weekend_file_count          3185 non-null   float64
dtypes: float64(7), int64(4), str(1)
memory usage: 320.9 KB

In [58]:
file_profile.describe()

,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files,unique_pcs,after_hours_file_activity,weekend_file_count
count,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000,3185.000000
mean,632.616327,206.436421,227.773312,78.846468,119.560126,183.590895,305.065306,184.878179,3.621350,40.787755,30.309576
std,1616.590455,370.776011,697.034802,242.806898,363.940130,552.356694,914.990412,470.379495,34.896083,192.889405,209.792955
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,26.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.000000,1.000000,0.000000,0.000000
50%,66.000000,65.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000,1.000000,2.000000,0.000000
75%,401.000000,185.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,1.000000,12.000000,0.000000
max,13882.000000,3413.000000,5664.000000,3498.000000,2763.000000,5296.000000,7045.000000,6281.000000,562.000000,2463.000000,3663.000000

In [59]:
# Save File Features
FEATURE_PATH = Path("../DATA/features")
FEATURE_PATH.mkdir(parents=True, exist_ok=True)

file_profile.to_csv(
    FEATURE_PATH / "file_features.csv",
    index=False
)

In [60]:
# Verify Saved File
saved_file = pd.read_csv("../DATA/features/file_features.csv")

saved_file.head()

,user,total_file_events,file_open_count,file_copy_count,file_write_count,file_delete_count,files_to_removable_media,files_from_removable_media,unique_files,unique_pcs,after_hours_file_activity,weekend_file_count
0,AAB0162,30,30,0.0,0.0,0.0,0.0,0.0,8,1,4.0,0.0
1,AAB0398,36,36,0.0,0.0,0.0,0.0,0.0,7,1,2.0,0.0
2,AAC0610,1851,387,825.0,235.0,404.0,604.0,1056.0,641,1,8.0,0.0
3,AAC0668,62,62,0.0,0.0,0.0,0.0,0.0,8,1,0.0,0.0
4,AAC3270,8,8,0.0,0.0,0.0,0.0,0.0,2,1,0.0,0.0