In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
DATA_PATH = Path("../DATA/raw/CERT_R6.2/data")

psychometric = pd.read_csv(
    DATA_PATH / "psychometric.csv"
)

In [3]:
psychometric.head()

              employee_name  user_id   O   C   E   A   N
0  Nicholas Fletcher Pruitt  NFP2441  34  39  38  36  21
1     Abraham Dante Rodgers  ADR1517  36  39  13  19  27
2     Medge Wilma Blackburn  MWB4000  27  14  44  22  34
3     Meghan Laurel Salazar  MLS2856  35  49  22  45  28
4          Beau Todd Romero  BTR2026  15  15  41  39  27

In [4]:
psychometric.tail()

                  employee_name  user_id   O   C   E   A   N
3995  Alfreda Jeanette Stephens  AJS0616  33  18  38  44  33
3996        Zachery Oscar Mayer  ZOM0746  43  48  16  34  29
3997    Ginger Jeanette Trevino  GJT1292  46  26  13  35  28
3998     Benjamin Lucian Duncan  BLD2227  39  44  19  43  30
3999        Jarrod Louis Fields  JLF3219  22  41  17  26  37

In [5]:
psychometric.shape

(4000, 7)

In [6]:
psychometric.columns

Index(['employee_name', 'user_id', 'O', 'C', 'E', 'A', 'N'], dtype='str')

In [7]:
psychometric.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_name  4000 non-null   str
 1   user_id        4000 non-null   str
 2   O              4000 non-null   int64
 3   C              4000 non-null   int64
 4   E              4000 non-null   int64
 5   A              4000 non-null   int64
 6   N              4000 non-null   int64
dtypes: int64(5), str(2)
memory usage: 323.1 KB

In [8]:
psychometric.isnull().sum()

employee_name    0
user_id          0
O                0
C                0
E                0
A                0
N                0
dtype: int64

In [9]:
psychometric.duplicated().sum()

np.int64(0)

# Rename User ID Column

The psychometric dataset uses the column name **user_id**, whereas all other feature datasets use **user**.

To ensure consistency across all datasets, we rename **user_id** to **user**.

In [10]:
psychometric = psychometric.rename(
    columns={"user_id": "user"}
)

In [11]:
psychometric.columns

Index(['employee_name', 'user', 'O', 'C', 'E', 'A', 'N'], dtype='str')

In [12]:
# Check Personality Score Statistics
psychometric.describe()

                 O           C            E            A            N
count  4000.000000  4000.00000  4000.000000  4000.000000  4000.000000
mean     33.176750    31.12000    28.973500    29.079500    29.556000
std      10.544895    10.96689    11.134913    11.034905     4.966591
min      10.000000    10.00000    10.000000    10.000000    12.000000
25%      24.000000    21.00000    19.000000    19.000000    26.000000
50%      37.000000    34.00000    27.000000    28.000000    30.000000
75%      41.000000    40.00000    39.000000    39.000000    33.000000
max      50.000000    50.00000    50.000000    50.000000    50.000000

In [13]:
# Select Final Personality Features
psychometric_features = psychometric[
    [
        "user",
        "O",
        "C",
        "E",
        "A",
        "N"
    ]
]

In [14]:
psychometric_features.head()

      user   O   C   E   A   N
0  NFP2441  34  39  38  36  21
1  ADR1517  36  39  13  19  27
2  MWB4000  27  14  44  22  34
3  MLS2856  35  49  22  45  28
4  BTR2026  15  15  41  39  27

In [15]:
# Verify Final Personality Features
psychometric_features.head()

      user   O   C   E   A   N
0  NFP2441  34  39  38  36  21
1  ADR1517  36  39  13  19  27
2  MWB4000  27  14  44  22  34
3  MLS2856  35  49  22  45  28
4  BTR2026  15  15  41  39  27

In [16]:
psychometric_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   user    4000 non-null   str
 1   O       4000 non-null   int64
 2   C       4000 non-null   int64
 3   E       4000 non-null   int64
 4   A       4000 non-null   int64
 5   N       4000 non-null   int64
dtypes: int64(5), str(1)
memory usage: 215.0 KB

In [17]:
# Check for Missing Values
psychometric_features.isnull().sum()

user    0
O       0
C       0
E       0
A       0
N       0
dtype: int64

In [18]:
# Replace Missing Values (If Any)
psychometric_features = psychometric_features.fillna(0)

In [19]:
psychometric_features.isnull().sum()

user    0
O       0
C       0
E       0
A       0
N       0
dtype: int64

In [20]:
# Save Psychometric Features
FEATURE_PATH = Path("../DATA/features")
FEATURE_PATH.mkdir(parents=True, exist_ok=True)

psychometric_features.to_csv(
    FEATURE_PATH / "psychometric_features.csv",
    index=False
)

In [21]:
# Verify Saved Psychometric Features
saved_psychometric = pd.read_csv(
    "../DATA/features/psychometric_features.csv"
)

saved_psychometric.head()

      user   O   C   E   A   N
0  NFP2441  34  39  38  36  21
1  ADR1517  36  39  13  19  27
2  MWB4000  27  14  44  22  34
3  MLS2856  35  49  22  45  28
4  BTR2026  15  15  41  39  27