# Merge All Features

This notebook combines all engineered feature datasets into a single employee-level dataset.

Every row represents one employee, while every column represents one behavioral or personality feature.

In [2]:
import pandas as pd
from pathlib import Path

In [3]:
FEATURE_PATH = Path("../DATA/features")

In [4]:
# Load All Feature Files
employee = pd.read_csv(
    FEATURE_PATH / "employee_profile.csv"
)

device = pd.read_csv(
    FEATURE_PATH / "device_features.csv"
)

email = pd.read_csv(
    FEATURE_PATH / "email_features.csv"
)

file = pd.read_csv(
    FEATURE_PATH / "file_features.csv"
)

http = pd.read_csv(
    FEATURE_PATH / "http_features.csv"
)

psychometric = pd.read_csv(
    FEATURE_PATH / "psychometric_features.csv"
)

In [5]:
# Verify Loaded Datasets
print("Employee :", employee.shape)
print("Device :", device.shape)
print("Email :", email.shape)
print("File :", file.shape)
print("HTTP :", http.shape)
print("Psychometric :", psychometric.shape)

Employee : (4000, 12)
Device : (788, 6)
Email : (4000, 8)
File : (3185, 12)
HTTP : (4000, 9)
Psychometric : (4000, 6)

# Merge Employee and Device Features

The Employee Profile dataset will be used as the base dataset.

We first merge the device features using the common **user** column.

In [6]:
merged_data = employee.merge(
    device,
    on="user",
    how="left"
)

In [7]:
# Merge Email Features
merged_data = merged_data.merge(
    email,
    on="user",
    how="left"
)

In [8]:
merged_data.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs,working_days,avg_events_per_day,first_login_hour,...,total_disconnects,after_hours_device_events,weekend_device_events,total_email_events,total_email_sent,after_hours_email_count,weekend_email_count,attachment_email_count,average_email_size_kb,average_recipient_count
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,NaN,NaN,NaN,3146,1122,440,0,590,349.985317,1.915766
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,NaN,NaN,NaN,3811,1348,698,0,1223,587.658355,1.889530
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,349.0,8.0,0.0,1052,388,16,0,375,530.789627,1.999049
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,NaN,NaN,NaN,3115,1093,23,0,689,377.849683,1.980096
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,NaN,NaN,NaN,344,120,0,0,170,846.968435,1.982558

In [9]:
# Merge File Features
merged_data = merged_data.merge(
    file,
    on="user",
    how="left"
)

In [10]:
# Merge HTTP Features
merged_data = merged_data.merge(
    http,
    on="user",
    how="left"
)
merged_data.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,...,after_hours_file_activity,weekend_file_count,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,4.0,0.0,33725,33725,0,0,4277,0,144,1
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,2.0,0.0,40584,40584,0,0,7128,0,351,1
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,8.0,0.0,10324,10324,0,0,240,0,267,1
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,0.0,0.0,33820,33820,0,0,320,0,227,1
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,0.0,0.0,3560,3560,0,0,0,0,60,1

In [11]:
# Verify Intermediate Merged Dataset
merged_data.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,...,after_hours_file_activity,weekend_file_count,total_http_events,http_visit_count,http_download_count,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,4.0,0.0,33725,33725,0,0,4277,0,144,1
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,2.0,0.0,40584,40584,0,0,7128,0,351,1
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,8.0,0.0,10324,10324,0,0,240,0,267,1
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,0.0,0.0,33820,33820,0,0,320,0,227,1
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,0.0,0.0,3560,3560,0,0,0,0,60,1

In [12]:
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 43 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user                        4000 non-null   str
 1   total_events                4000 non-null   int64
 2   total_logons                4000 non-null   int64
 3   total_logoffs               4000 non-null   int64
 4   after_hours_events          4000 non-null   float64
 5   weekend_events              4000 non-null   float64
 6   unique_pcs_x                4000 non-null   int64
 7   working_days                4000 non-null   int64
 8   avg_events_per_day          4000 non-null   float64
 9   first_login_hour            4000 non-null   int64
 10  last_logout_hour            4000 non-null   int64
 11  work_duration_hours         4000 non-null   int64
 12  total_device_events         788 non-null    float64
 13  total_connects              788 non-null    float64
 14  total_disconnects           788 non-null    float64
 15  after_hours_device_events   788 non-null    float64
 16  weekend_device_events       788 non-null    float64
 17  total_email_events          4000 non-null   int64
 18  total_email_sent            4000 non-null   int64
 19  after_hours_email_count     4000 non-null   int64
 20  weekend_email_count         4000 non-null   int64
 21  attachment_email_count      4000 non-null   int64
 22  average_email_size_kb       4000 non-null   float64
 23  average_recipient_count     4000 non-null   float64
 24  total_file_events           3185 non-null   float64
 25  file_open_count             3185 non-null   float64
 26  file_copy_count             3185 non-null   float64
 27  file_write_count            3185 non-null   float64
 28  file_delete_count           3185 non-null   float64
 29  files_to_removable_media    3185 non-null   float64
 30  files_from_removable_media  3185 non-null   float64
 31  unique_files                3185 non-null   float64
 32  unique_pcs_y                3185 non-null   float64
 33  after_hours_file_activity   3185 non-null   float64
 34  weekend_file_count          3185 non-null   float64
 35  total_http_events           4000 non-null   int64
 36  http_visit_count            4000 non-null   int64
 37  http_download_count         4000 non-null   int64
 38  http_upload_count           4000 non-null   int64
 39  after_hours_http_count      4000 non-null   int64
 40  weekend_http_count          4000 non-null   int64
 41  unique_urls                 4000 non-null   int64
 42  unique_http_pcs             4000 non-null   int64
dtypes: float64(21), int64(21), str(1)
memory usage: 1.3 MB

In [13]:
merged_data.shape

(4000, 43)

# Merge Psychometric Features

The final step is to merge the psychometric (Big Five Personality) features with the behavioral dataset.

This creates a complete employee profile containing both behavioral and personality information.

In [14]:
merged_data = merged_data.merge(
    psychometric,
    on="user",
    how="left"
)
merged_data.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,...,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs,O,C,E,A,N
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,0,4277,0,144,1,45,36,33,15,33
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,0,7128,0,351,1,16,38,16,26,34
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,0,240,0,267,1,46,35,50,42,31
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,0,320,0,227,1,38,48,37,38,37
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,0,0,0,60,1,26,37,42,45,30

In [15]:
# Check for Duplicate Employees
duplicate_users = merged_data["user"].duplicated().sum()

print("Duplicate Users:", duplicate_users)

Duplicate Users: 0

In [16]:
# Handle Missing Values
merged_data = merged_data.fillna(0)

In [17]:
merged_data.isnull().sum()

user                          0
total_events                  0
total_logons                  0
total_logoffs                 0
after_hours_events            0
weekend_events                0
unique_pcs_x                  0
working_days                  0
avg_events_per_day            0
first_login_hour              0
last_logout_hour              0
work_duration_hours           0
total_device_events           0
total_connects                0
total_disconnects             0
after_hours_device_events     0
weekend_device_events         0
total_email_events            0
total_email_sent              0
after_hours_email_count       0
weekend_email_count           0
attachment_email_count        0
average_email_size_kb         0
average_recipient_count       0
total_file_events             0
file_open_count               0
file_copy_count               0
file_write_count              0
file_delete_count             0
files_to_removable_media      0
files_from_removable_media    0
unique_files                  0
unique_pcs_y                  0
after_hours_file_activity     0
weekend_file_count            0
total_http_events             0
http_visit_count              0
http_download_count           0
http_upload_count             0
after_hours_http_count        0
weekend_http_count            0
unique_urls                   0
unique_http_pcs               0
O                             0
C                             0
E                             0
A                             0
N                             0
dtype: int64

In [18]:
# Verify Final Merged Dataset
merged_data.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,...,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs,O,C,E,A,N
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,0,4277,0,144,1,45,36,33,15,33
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,0,7128,0,351,1,16,38,16,26,34
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,0,240,0,267,1,46,35,50,42,31
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,0,320,0,227,1,38,48,37,38,37
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,0,0,0,60,1,26,37,42,45,30

In [19]:
merged_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 48 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   user                        4000 non-null   str
 1   total_events                4000 non-null   int64
 2   total_logons                4000 non-null   int64
 3   total_logoffs               4000 non-null   int64
 4   after_hours_events          4000 non-null   float64
 5   weekend_events              4000 non-null   float64
 6   unique_pcs_x                4000 non-null   int64
 7   working_days                4000 non-null   int64
 8   avg_events_per_day          4000 non-null   float64
 9   first_login_hour            4000 non-null   int64
 10  last_logout_hour            4000 non-null   int64
 11  work_duration_hours         4000 non-null   int64
 12  total_device_events         4000 non-null   float64
 13  total_connects              4000 non-null   float64
 14  total_disconnects           4000 non-null   float64
 15  after_hours_device_events   4000 non-null   float64
 16  weekend_device_events       4000 non-null   float64
 17  total_email_events          4000 non-null   int64
 18  total_email_sent            4000 non-null   int64
 19  after_hours_email_count     4000 non-null   int64
 20  weekend_email_count         4000 non-null   int64
 21  attachment_email_count      4000 non-null   int64
 22  average_email_size_kb       4000 non-null   float64
 23  average_recipient_count     4000 non-null   float64
 24  total_file_events           4000 non-null   float64
 25  file_open_count             4000 non-null   float64
 26  file_copy_count             4000 non-null   float64
 27  file_write_count            4000 non-null   float64
 28  file_delete_count           4000 non-null   float64
 29  files_to_removable_media    4000 non-null   float64
 30  files_from_removable_media  4000 non-null   float64
 31  unique_files                4000 non-null   float64
 32  unique_pcs_y                4000 non-null   float64
 33  after_hours_file_activity   4000 non-null   float64
 34  weekend_file_count          4000 non-null   float64
 35  total_http_events           4000 non-null   int64
 36  http_visit_count            4000 non-null   int64
 37  http_download_count         4000 non-null   int64
 38  http_upload_count           4000 non-null   int64
 39  after_hours_http_count      4000 non-null   int64
 40  weekend_http_count          4000 non-null   int64
 41  unique_urls                 4000 non-null   int64
 42  unique_http_pcs             4000 non-null   int64
 43  O                           4000 non-null   int64
 44  C                           4000 non-null   int64
 45  E                           4000 non-null   int64
 46  A                           4000 non-null   int64
 47  N                           4000 non-null   int64
dtypes: float64(21), int64(26), str(1)
memory usage: 1.5 MB

In [20]:
merged_data.describe()

,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,last_logout_hour,...,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs,O,C,E,A,N
count,4000.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.000000,4000.000000,4000.000000,4000.000000,4000.0,4000.000000,4000.00000,4000.000000,4000.000000,4000.000000
mean,882.571250,487.23325,395.338000,345.264250,20.054500,38.791000,348.502500,2.527725,6.441000,17.926000,...,52.600250,1805.781750,579.065000,619.382000,1.0,33.176750,31.12000,28.973500,29.079500,29.556000
std,411.251398,245.38082,182.557717,329.481241,72.046594,144.937135,62.842571,1.063629,2.435673,2.118879,...,185.499904,2300.699227,2521.284742,1572.559794,0.0,10.544895,10.96689,11.134913,11.034905,4.966591
min,42.000000,21.00000,21.000000,0.000000,0.000000,1.000000,21.000000,1.994382,0.000000,14.000000,...,0.000000,0.000000,0.000000,42.000000,1.0,10.000000,10.00000,10.000000,10.000000,12.000000
25%,712.000000,356.00000,356.000000,166.000000,0.000000,1.000000,356.000000,2.000000,7.000000,17.000000,...,0.000000,195.000000,0.000000,165.000000,1.0,24.000000,21.00000,19.000000,19.000000,26.000000
50%,712.000000,356.00000,356.000000,356.000000,0.000000,1.000000,356.000000,2.000000,7.000000,18.000000,...,0.000000,779.000000,0.000000,232.000000,1.0,37.000000,34.00000,27.000000,28.000000,30.000000
75%,996.000000,637.00000,395.000000,373.000000,0.000000,19.000000,356.000000,2.800112,8.000000,18.000000,...,0.000000,2721.250000,0.000000,326.000000,1.0,41.000000,40.00000,39.000000,39.000000,33.000000
max,4151.000000,2256.00000,1895.000000,2763.000000,1002.000000,1226.000000,515.000000,9.794749,9.000000,23.000000,...,1713.000000,23406.000000,33060.000000,15610.000000,1.0,50.000000,50.00000,50.000000,50.000000,50.000000

In [21]:
merged_data.shape

(4000, 48)

In [22]:
# Save Final Merged Dataset
FEATURE_PATH = Path("../DATA/features")
FEATURE_PATH.mkdir(parents=True, exist_ok=True)

merged_data.to_csv(
    FEATURE_PATH / "merged_features.csv",
    index=False
)

In [23]:
saved_merged = pd.read_csv("../DATA/features/merged_features.csv")
saved_merged.head()

,user,total_events,total_logons,total_logoffs,after_hours_events,weekend_events,unique_pcs_x,working_days,avg_events_per_day,first_login_hour,...,http_upload_count,after_hours_http_count,weekend_http_count,unique_urls,unique_http_pcs,O,C,E,A,N
0,AAB0162,711,355,356,705.0,0.0,1,356,1.997191,7,...,0,4277,0,144,1,45,36,33,15,33
1,AAB0398,712,356,356,356.0,0.0,1,356,2.000000,6,...,0,7128,0,351,1,16,38,16,26,34
2,AAC0610,1052,665,387,222.0,5.0,1,360,2.922222,0,...,0,240,0,267,1,46,35,50,42,31
3,AAC0668,712,356,356,158.0,0.0,1,356,2.000000,7,...,0,320,0,227,1,38,48,37,38,37
4,AAC3270,712,356,356,0.0,0.0,1,356,2.000000,8,...,0,0,0,60,1,26,37,42,45,30

In [24]:
merged_data = employee.copy()